### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ApexArtist** [abdelazizmirasoft/bot-followfast#1]
Traceback (most recent call last):
  File "C:\Python\FollowFast\screenSearch.py", line 99, in <module>
    pos = pyautogui.locateCenterOnScreen('buttons/'+b)#If the file is not a png file it will not work
  File "C:\Python\FollowFast\venv\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Python\FollowFast\venv\lib\site-packages\pyautogui\__init__.py", line 207, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
  File "C:\Python\FollowFast\venv\lib\site-packages\pyscreeze\__init__.py", line 400, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "C:\Python\FollowFast\venv\lib\site-packages\pyscreeze\__init__.py", line 359, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "C:\Python\FollowFast\venv\lib\site-packages\pyscreeze\__init__.py", line 134, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.

Process finished with exit code 1

**Comment by abdelazizmirasoft** [comment]
https://user-images.githubusercontent.com/54293593/103275212-fd2d8000-49c3-11eb-8132-9764e6d7b6e8.mp4

Please try first of all to follow the steps in the attached video to create all buttons images in the buttons folder to get their size on your screen.
For the issue you got, please be sure that: 
- Pillow package is installed in your environment:  `pip install Pillow`
